apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-singer-instrument
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-singer-instrument
  template:
    metadata:
      labels:
        app: app-singer-instrument
    spec:
      containers:
        - name: app-singer-instrument
          image: milekaterine/app-singer-instrument:latest
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: distribuida
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app-singer-instrument-service
spec:
  type: ClusterIP
  selector:
    app: app-singer-instrument
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
